#==========================================================================
#
#   The PyRISC Project
#
#   SNURISC: A RISC-V ISA Simulator
#
#   Classes for hardware components: RegisterFile, Register, and Memory. 
#
#   Jin-Soo Kim
#   Systems Software and Architecture Laboratory
#   Seoul National University
#   http://csl.snu.ac.kr
#
#==========================================================================

from consts import *


csr_dictionary = {
    
    CSR_FFLAGS          : "fflags",
    CSR_FRM             : "frm",
    CSR_FCSR            : "fcsr",
    CSR_USTATUS         : "ustatus",
    CSR_UIE             : "uie",
    CSR_UTVEC           : "utvec",
    CSR_VSTART          : "vstart",
    CSR_VXSAT           : "vxsat",
    CSR_VXRM            : "vxrm",
    CSR_USCRATCH        : "uscratch",
    CSR_UEPC            : "uepc",
    CSR_UCAUSE          : "ucause",
    CSR_UTVAL           : "utval",
    CSR_UIP             : "uip",
    CSR_CYCLE           : "cycle",
    CSR_TIME            : "time",
    CSR_INSTRET         : "instret",
    CSR_HPMCOUNTER3     : "hpmcounter3",
    CSR_HPMCOUNTER4     : "hpmcounter4",
    CSR_HPMCOUNTER5     : "hpmcounter5",
    CSR_HPMCOUNTER6     : "hpmcounter6",
    CSR_HPMCOUNTER7     : "hpmcounter7",
    CSR_HPMCOUNTER8     : "hpmcounter8",
    CSR_HPMCOUNTER9     : "hpmcounter9",
    CSR_HPMCOUNTER10    : "hpmcounter10",
    CSR_HPMCOUNTER11    : "hpmcounter11",
    CSR_HPMCOUNTER12    : "hpmcounter12",
    CSR_HPMCOUNTER13    : "hpmcounter13",
    CSR_HPMCOUNTER14    : "hpmcounter14",
    CSR_HPMCOUNTER15    : "hpmcounter15",
    CSR_HPMCOUNTER16    : "hpmcounter16",
    CSR_HPMCOUNTER17    : "hpmcounter17",
    CSR_HPMCOUNTER18    : "hpmcounter18",
    CSR_HPMCOUNTER19    : "hpmcounter19",
    CSR_HPMCOUNTER20    : "hpmcounter20",
    CSR_HPMCOUNTER21    : "hpmcounter21",
    CSR_HPMCOUNTER22    : "hpmcounter22",
    CSR_HPMCOUNTER23    : "hpmcounter23",
    CSR_HPMCOUNTER24    : "hpmcounter24",
    CSR_HPMCOUNTER25    : "hpmcounter25",
    CSR_HPMCOUNTER26    : "hpmcounter26",
    CSR_HPMCOUNTER27    : "hpmcounter27",
    CSR_HPMCOUNTER28    : "hpmcounter28",
    CSR_HPMCOUNTER29    : "hpmcounter29",
    CSR_HPMCOUNTER30    : "hpmcounter30",
    CSR_HPMCOUNTER31    : "hpmcounter31",
    CSR_VL              : "vl",
    CSR_VTYPE           : "vtype",
    CSR_VLENB           : "vlenb",
    CSR_SSTATUS         : "sstatus",
    CSR_SIE             : "sie",
    CSR_STVEC           : "stvec",
    CSR_SCOUNTEREN      : "scounteren",
    CSR_SSCRATCH        : "sscratch",
    CSR_SEPC            : "sepc",
    CSR_SCAUSE          : "scause",
    CSR_STVAL           : "stval",
    CSR_SIP             : "sip",
    CSR_SATP            : "satp",
    CSR_VSSTATUS        : "vsstatus",
    CSR_VSIE            : "vsie",
    CSR_VSTVEC          : "vstvec",
    CSR_VSSCRATCH       : "vsscratch",
    CSR_VSEPC           : "vsepc",
    CSR_VSCAUSE         : "vscause",
    CSR_VSTVAL          : "vstcal",
    CSR_VSIP            : "vsip",
    CSR_VSATP           : "vsatp",
    CSR_HSTATUS         : "hstatus",
    CSR_HEDELEG         : "hedeleg",
    CSR_HIDELEG         : "hideleg",
    CSR_HCOUNTEREN      : "hcounteren",
    CSR_HGATP           : "hgatp",
    CSR_UTVT            : "utvt",
    CSR_UNXTI           : "unxti",
    CSR_UINTSTATUS      : "uintstatus",
    CSR_USCRATCHCSW     : "uscratchcsw",
    CSR_USCRATCHCSWL    : "uscratchcswl",
    CSR_STVT            : "stvt",
    CSR_SNXTI           : "snxti",
    CSR_SINTSTATUS      : "sintstatus",
    CSR_SSCRATCHCSW     : "sscratchcsw",
    CSR_SSCRATCHCSWL    : "sscratchcswl",
    CSR_MTVT            : "mtvt",
    CSR_MNXTI           : "mnxti",
    CSR_MINTSTATUS      : "mintstatus",
    CSR_MSCRATCHCSW     : "mscratchcsw",
    CSR_MSCRATCHCSWL    : "mscratchcswl",

    # Machine Trap Setup

    CSR_MSTATUS         : "mstatus",
    CSR_MISA            : "misa",
    CSR_MEDELEG         : "medeleg",
    CSR_MIDELEG         : "mideleg",
    CSR_MIE             : "mie",
    CSR_MTVEC           : "mtvec",
    CSR_MCOUNTEREN      : "mcounteren",

    # Machine Trap Handling

    CSR_MSCRATCH        : "mscratch",
    CSR_MEPC            : "mepc",
    CSR_MCAUSE          : "mcause",
    CSR_MTVAL           : "mtval",
    CSR_MIP             : "mip",

    # Machine Memory Protection

    CSR_PMPCFG0         : "pmpcfg0",
    CSR_PMPCFG1         : "pmpcfg1",
    CSR_PMPCFG2         : "pmpcfg2",
    CSR_PMPCFG3         : "pmpcfg3",

    CSR_PMPADDR0        : "pmpaddr0",
    CSR_PMPADDR1        : "pmpaddr1",
    CSR_PMPADDR2        : "pmpaddr2",
    CSR_PMPADDR3        : "pmpaddr3",
    CSR_PMPADDR4        : "pmpaddr4",
    CSR_PMPADDR5        : "pmpaddr5",
    CSR_PMPADDR6        : "pmpaddr6",
    CSR_PMPADDR7        : "pmpaddr7",
    CSR_PMPADDR8        : "pmpaddr8",
    CSR_PMPADDR9        : "pmpaddr9",
    CSR_PMPADDR10       : "pmpaddr10",
    CSR_PMPADDR11       : "pmpaddr11",
    CSR_PMPADDR12       : "pmpaddr12",
    CSR_PMPADDR13       : "pmpaddr13",
    CSR_PMPADDR14       : "pmpaddr14",
    CSR_PMPADDR15       : "pmpaddr15",

    CSR_TSELECT         : "tselect",
    CSR_TDATA1          : "tdata1",
    CSR_TDATA2          : "tdata2",
    CSR_TDATA3          : "tdata3",
    CSR_DCSR            : "dcsr",
    CSR_DPC             : "dpc",
    CSR_DSCRATCH        : "dscratch",
    
    # Machine Counter/Timers

    CSR_MCYCLE          : "mcycle",
    CSR_MINSTRET        : "minstret",
    CSR_MHPMCOUNTER3    : "mhpcounter3",
    CSR_MHPMCOUNTER4    : "mhpcounter4",
    CSR_MHPMCOUNTER5    : "mhpcounter5",
    CSR_MHPMCOUNTER6    : "mhpcounter6",
    CSR_MHPMCOUNTER7    : "mhpcounter7",
    CSR_MHPMCOUNTER8    : "mhpcounter8",
    CSR_MHPMCOUNTER9    : "mhpcounter9",
    CSR_MHPMCOUNTER10   : "mhpcounter10",
    CSR_MHPMCOUNTER11   : "mhpcounter11",
    CSR_MHPMCOUNTER12   : "mhpcounter12",
    CSR_MHPMCOUNTER13   : "mhpcounter13",
    CSR_MHPMCOUNTER14   : "mhpcounter14",
    CSR_MHPMCOUNTER15   : "mhpcounter15",
    CSR_MHPMCOUNTER16   : "mhpcounter16",
    CSR_MHPMCOUNTER17   : "mhpcounter17",
    CSR_MHPMCOUNTER18   : "mhpcounter18",
    CSR_MHPMCOUNTER19   : "mhpcounter19",
    CSR_MHPMCOUNTER20   : "mhpcounter20",
    CSR_MHPMCOUNTER21   : "mhpcounter21",
    CSR_MHPMCOUNTER22   : "mhpcounter22",
    CSR_MHPMCOUNTER23   : "mhpcounter23",
    CSR_MHPMCOUNTER24   : "mhpcounter24",
    CSR_MHPMCOUNTER25   : "mhpcounter25",
    CSR_MHPMCOUNTER26   : "mhpcounter26",
    CSR_MHPMCOUNTER27   : "mhpcounter27",
    CSR_MHPMCOUNTER28   : "mhpcounter28",
    CSR_MHPMCOUNTER29   : "mhpcounter29",
    CSR_MHPMCOUNTER30   : "mhpcounter30",
    CSR_MHPMCOUNTER31   : "mhpcounter31",

    # Machine Counter Setup

    # CSR_MCOUNTINHIBIT   : "mcountinhibit",     # not included in spike encoding
    CSR_MHPEVENT3       : "mhpevent3",
    CSR_MHPEVENT4       : "mhpevent4",
    CSR_MHPEVENT5       : "mhpevent5",
    CSR_MHPEVENT6       : "mhpevent6",
    CSR_MHPEVENT7       : "mhpevent7",
    CSR_MHPEVENT8       : "mhpevent8",
    CSR_MHPEVENT9       : "mhpevent9",
    CSR_MHPEVENT10      : "mhpevent10",
    CSR_MHPEVENT11      : "mhpevent11",
    CSR_MHPEVENT12      : "mhpevent12",
    CSR_MHPEVENT13      : "mhpevent13",
    CSR_MHPEVENT14      : "mhpevent14",
    CSR_MHPEVENT15      : "mhpevent15",
    CSR_MHPEVENT16      : "mhpevent16",
    CSR_MHPEVENT17      : "mhpevent17",
    CSR_MHPEVENT18      : "mhpevent18",
    CSR_MHPEVENT19      : "mhpevent19",
    CSR_MHPEVENT20      : "mhpevent20",
    CSR_MHPEVENT21      : "mhpevent21",
    CSR_MHPEVENT22      : "mhpevent22",
    CSR_MHPEVENT23      : "mhpevent23",
    CSR_MHPEVENT24      : "mhpevent24",
    CSR_MHPEVENT25      : "mhpevent25",
    CSR_MHPEVENT26      : "mhpevent26",
    CSR_MHPEVENT27      : "mhpevent27",
    CSR_MHPEVENT28      : "mhpevent28",
    CSR_MHPEVENT29      : "mhpevent29",
    CSR_MHPEVENT30      : "mhpevent30",
    CSR_MHPEVENT31      : "mhpevent31",

    # Machine Information Registers
    CSR_MVENDORID       : "mvendorid",
    CSR_MARCHID         : "marchid",
    CSR_MIMPID          : "mimpid",
    CSR_MHARTID         : "mhartid",

    CSR_CYCLEH          : "cycleh",
    CSR_TIMEH           : "timeh",
    CSR_INSTRETH        : "instreth",
    CSR_HPMCOUNTER3H    : "hpmcounter3h",
    CSR_HPMCOUNTER4H    : "hpmcounter4h",
    CSR_HPMCOUNTER5H    : "hpmcounter5h",
    CSR_HPMCOUNTER6H    : "hpmcounter6h",
    CSR_HPMCOUNTER7H    : "hpmcounter7h",
    CSR_HPMCOUNTER8H    : "hpmcounter8h",
    CSR_HPMCOUNTER9H    : "hpmcounter9h",
    CSR_HPMCOUNTER10H   : "hpmcounter10h",
    CSR_HPMCOUNTER11H   : "hpmcounter11h",
    CSR_HPMCOUNTER12H   : "hpmcounter12h",
    CSR_HPMCOUNTER13H   : "hpmcounter13h",
    CSR_HPMCOUNTER14H   : "hpmcounter14h",
    CSR_HPMCOUNTER15H   : "hpmcounter15h",
    CSR_HPMCOUNTER16H   : "hpmcounter16h",
    CSR_HPMCOUNTER17H   : "hpmcounter17h",
    CSR_HPMCOUNTER18H   : "hpmcounter18h",
    CSR_HPMCOUNTER19H   : "hpmcounter19h",
    CSR_HPMCOUNTER20H   : "hpmcounter20h",
    CSR_HPMCOUNTER21H   : "hpmcounter21h",
    CSR_HPMCOUNTER22H   : "hpmcounter22h",
    CSR_HPMCOUNTER23H   : "hpmcounter23h",
    CSR_HPMCOUNTER24H   : "hpmcounter24h",
    CSR_HPMCOUNTER25H   : "hpmcounter25h",
    CSR_HPMCOUNTER26H   : "hpmcounter26h",
    CSR_HPMCOUNTER27H   : "hpmcounter27h",
    CSR_HPMCOUNTER28H   : "hpmcounter28h",
    CSR_HPMCOUNTER29H   : "hpmcounter29h",
    CSR_HPMCOUNTER30H   : "hpmcounter30h",
    CSR_HPMCOUNTER31H   : "hpmcounter31h",
    CSR_MCYCLEH         : "mcycleh",
    CSR_MINSTRETH       : "minstreth",
    CSR_MHPMCOUNTER3H   : "mhpmcounter3h",
    CSR_MHPMCOUNTER4H   : "mhpmcounter4h",
    CSR_MHPMCOUNTER5H   : "mhpmcounter5h",
    CSR_MHPMCOUNTER6H   : "mhpmcounter6h",
    CSR_MHPMCOUNTER7H   : "mhpmcounter7h",
    CSR_MHPMCOUNTER8H   : "mhpmcounter8h",
    CSR_MHPMCOUNTER9H   : "mhpmcounter9h",
    CSR_MHPMCOUNTER10H  : "mhpmcounter10h",
    CSR_MHPMCOUNTER11H  : "mhpmcounter11h",
    CSR_MHPMCOUNTER12H  : "mhpmcounter12h",
    CSR_MHPMCOUNTER13H  : "mhpmcounter13h",
    CSR_MHPMCOUNTER14H  : "mhpmcounter14h",
    CSR_MHPMCOUNTER15H  : "mhpmcounter15h",
    CSR_MHPMCOUNTER16H  : "mhpmcounter16h",
    CSR_MHPMCOUNTER17H  : "mhpmcounter17h",
    CSR_MHPMCOUNTER18H  : "mhpmcounter18h",
    CSR_MHPMCOUNTER19H  : "mhpmcounter19h",
    CSR_MHPMCOUNTER20H  : "mhpmcounter20h",
    CSR_MHPMCOUNTER21H  : "mhpmcounter21h",
    CSR_MHPMCOUNTER22H  : "mhpmcounter22h",
    CSR_MHPMCOUNTER23H  : "mhpmcounter23h",
    CSR_MHPMCOUNTER24H  : "mhpmcounter24h",
    CSR_MHPMCOUNTER25H  : "mhpmcounter25h",
    CSR_MHPMCOUNTER26H  : "mhpmcounter26h",
    CSR_MHPMCOUNTER27H  : "mhpmcounter27h",
    CSR_MHPMCOUNTER28H  : "mhpmcounter28h",
    CSR_MHPMCOUNTER29H  : "mhpmcounter29h",
    CSR_MHPMCOUNTER30H  : "mhpmcounter30h",
    CSR_MHPMCOUNTER31H  : "mhpmcounter31h",
}