#==========================================================================
#
#   The PyRISC Project
#
#   SNURISC: A RISC-V ISA Simulator
#
#   Classes for hardware components: RegisterFile, Register, and Memory. 
#
#   Jin-Soo Kim
#   Systems Software and Architecture Laboratory
#   Seoul National University
#   http://csl.snu.ac.kr
#
#==========================================================================


from consts import *
from components import *
from csrdict import *

class PrivReg(object):

    def __init__(self):

        self.fflags         = Register()
        self.frm            = Register()
        self.fcsr           = Register()
        self.ustatus        = Register()
        self.uie            = Register()
        self.utvec          = Register()
        self.vstart         = Register()
        self.vxsat          = Register()
        self.vxrm           = Register()
        self.uscratch       = Register()
        self.uepc           = Register()
        self.ucause         = Register()
        self.utval          = Register()
        self.uip            = Register()
        self.cycle          = Register()
        self.time           = Register()
        self.instret        = Register()
        self.hpmcounter3    = Register()
        self.hpmcounter4    = Register()
        self.hpmcounter5    = Register()
        self.hpmcounter6    = Register()
        self.hpmcounter7    = Register()
        self.hpmcounter8    = Register()
        self.hpmcounter9    = Register()
        self.hpmcounter10   = Register()
        self.hpmcounter11   = Register()
        self.hpmcounter12   = Register()
        self.hpmcounter13   = Register()
        self.hpmcounter14   = Register()
        self.hpmcounter15   = Register()
        self.hpmcounter16   = Register()
        self.hpmcounter17   = Register()
        self.hpmcounter18   = Register()
        self.hpmcounter19   = Register()
        self.hpmcounter20   = Register()
        self.hpmcounter21   = Register()
        self.hpmcounter22   = Register()
        self.hpmcounter23   = Register()
        self.hpmcounter24   = Register()
        self.hpmcounter25   = Register()
        self.hpmcounter26   = Register()
        self.hpmcounter27   = Register()
        self.hpmcounter28   = Register()
        self.hpmcounter29   = Register()
        self.hpmcounter30   = Register()
        self.hpmcounter31   = Register()
        self.vl             = Register()
        self.vtype          = Register()
        self.vlenb          = Register()
        self.sstatus        = Register()
        self.sie            = Register()
        self.stvec          = Register()        
        self.scounteren     = Register()
        self.sscratch       = Register()
        self.sepc           = Register()
        self.scause         = Register()
        self.stval          = Register()
        self.sip            = Register()
        self.satp           = Register()
        self.vsstatus       = Register()
        self.vsie           = Register()
        self.vstvec         = Register()
        self.vsscratch      = Register()
        self.vsepc          = Register()
        self.vscause        = Register()
        self.vstval         = Register()
        self.vsip           = Register()
        self.vsatp          = Register()
        self.hstatus        = Register()
        self.hedeleg        = Register()
        self.hideleg        = Register()
        self.hcounteren     = Register()
        self.hgatp          = Register()
        self.utvt           = Register()
        self.unxti          = Register()
        self.uintstatus     = Register()
        self.uscratchcsw    = Register()
        self.uscratchcswl   = Register()
        self.stvt           = Register()
        self.snxti          = Register()
        self.sintstatus     = Register()
        self.sscratchcsw    = Register()
        self.sscratchcswl   = Register()
        self.mtvt           = Register()
        self.mnxti          = Register()
        self.mintstatus     = Register()
        self.mscratchcsw    = Register()
        self.mscratchcswl   = Register()
        self.mstatus        = Register()
        self.misa           = Register()
        self.misa.write(0x40140100)
        self.medeleg        = Register()
        self.mideleg        = Register()
        self.mie            = Register()
        self.mtvec          = Register()
        self.mcounteren     = Register()
        self.mscratch       = Register()
        self.mepc           = Register()
        self.mcause         = Register()
        self.mtval          = Register()
        self.mip            = Register()
        self.pmpcfg0        = Register()
        self.pmpcfg1        = Register()
        self.pmpcfg2        = Register()
        self.pmpcfg3        = Register()
        self.pmpaddr0       = Register()
        self.pmpaddr1       = Register()
        self.pmpaddr2       = Register()
        self.pmpaddr3       = Register()
        self.pmpaddr4       = Register()
        self.pmpaddr5       = Register()
        self.pmpaddr6       = Register()
        self.pmpaddr7       = Register()
        self.pmpaddr8       = Register()
        self.pmpaddr9       = Register()
        self.pmpaddr10      = Register()
        self.pmpaddr11      = Register()
        self.pmpaddr12      = Register()
        self.pmpaddr13      = Register()
        self.pmpaddr14      = Register()
        self.pmpaddr15      = Register()
        self.tselect        = Register()
        self.tdata1         = Register()
        self.tdata2         = Register()
        self.tdata3         = Register()
        self.dcsr           = Register()
        self.dpc            = Register()
        self.dscratch       = Register()        #why dscratch0 & dscratch1?
        
        self.mcycle         = Register()
        self.minstret       = Register()  
        self.mhpmcounter3   = Register()
        self.mhpmcounter4   = Register()      
        self.mhpmcounter5   = Register()
        self.mhpmcounter6   = Register()      
        self.mhpmcounter7   = Register()
        self.mhpmcounter8   = Register()      
        self.mhpmcounter9   = Register()
        self.mhpmcounter10  = Register()      
        self.mhpmcounter11  = Register()      
        self.mhpmcounter12  = Register()      
        self.mhpmcounter13  = Register()      
        self.mhpmcounter14  = Register()      
        self.mhpmcounter15  = Register()      
        self.mhpmcounter16  = Register()      
        self.mhpmcounter17  = Register()      
        self.mhpmcounter18  = Register()      
        self.mhpmcounter19  = Register()      
        self.mhpmcounter20  = Register()      
        self.mhpmcounter21  = Register()      
        self.mhpmcounter22  = Register()      
        self.mhpmcounter23  = Register()      
        self.mhpmcounter24  = Register()      
        self.mhpmcounter25  = Register()      
        self.mhpmcounter26  = Register()      
        self.mhpmcounter27  = Register()      
        self.mhpmcounter28  = Register()      
        self.mhpmcounter29  = Register()      
        self.mhpmcounter30  = Register()      
        self.mhpmcounter31  = Register()      

        self.mhpevent3      = Register()
        self.mhpevent4      = Register()
        self.mhpevent5      = Register()
        self.mhpevent6      = Register()
        self.mhpevent7      = Register()
        self.mhpevent8      = Register()                
        self.mhpevent9      = Register()
        self.mhpevent10     = Register()
        self.mhpevent11     = Register()
        self.mhpevent12     = Register()
        self.mhpevent13     = Register()
        self.mhpevent14     = Register()
        self.mhpevent15     = Register()
        self.mhpevent16     = Register()
        self.mhpevent17     = Register()
        self.mhpevent18     = Register()
        self.mhpevent19     = Register()
        self.mhpevent20     = Register()
        self.mhpevent21     = Register()
        self.mhpevent22     = Register()
        self.mhpevent23     = Register()
        self.mhpevent24     = Register()
        self.mhpevent25     = Register()
        self.mhpevent26     = Register()
        self.mhpevent27     = Register()
        self.mhpevent28     = Register()
        self.mhpevent29     = Register()
        self.mhpevent30     = Register()
        self.mhpevent31     = Register()

        self.mvendorid      = Register()
        self.marchid        = Register()
        self.mimpid         = Register()
        self.mhartid        = Register()

        self.cycleh         = Register()
        self.timeh          = Register()
        self.instreth       = Register()
        self.hpmcounter3h   = Register()
        self.hpmcounter4h   = Register()
        self.hpmcounter5h   = Register()
        self.hpmcounter6h   = Register()
        self.hpmcounter7h   = Register()
        self.hpmcounter8h   = Register()
        self.hpmcounter9h   = Register()
        self.hpmcounter10h  = Register()
        self.hpmcounter11h  = Register()
        self.hpmcounter12h  = Register()
        self.hpmcounter13h  = Register()
        self.hpmcounter14h  = Register()
        self.hpmcounter15h  = Register()
        self.hpmcounter16h  = Register()
        self.hpmcounter17h  = Register()
        self.hpmcounter18h  = Register()
        self.hpmcounter19h  = Register()
        self.hpmcounter20h  = Register()
        self.hpmcounter21h  = Register()
        self.hpmcounter22h  = Register()
        self.hpmcounter23h  = Register()
        self.hpmcounter24h  = Register()
        self.hpmcounter25h  = Register()
        self.hpmcounter26h  = Register()
        self.hpmcounter27h  = Register()
        self.hpmcounter28h  = Register()
        self.hpmcounter29h  = Register()
        self.hpmcounter30h  = Register()
        self.hpmcounter31h  = Register()
        self.mcycleh        = Register()
        self.minstreth      = Register()
        self.mhpmcounter3h  = Register()
        self.mhpmcounter4h  = Register()
        self.mhpmcounter5h  = Register()
        self.mhpmcounter6h  = Register()
        self.mhpmcounter7h  = Register()
        self.mhpmcounter8h  = Register()
        self.mhpmcounter9h  = Register()
        self.mhpmcounter10h = Register()
        self.mhpmcounter11h = Register()
        self.mhpmcounter12h = Register()
        self.mhpmcounter13h = Register()
        self.mhpmcounter14h = Register()
        self.mhpmcounter15h = Register()
        self.mhpmcounter16h = Register()
        self.mhpmcounter17h = Register()
        self.mhpmcounter18h = Register()
        self.mhpmcounter19h = Register()
        self.mhpmcounter20h = Register()
        self.mhpmcounter21h = Register()
        self.mhpmcounter22h = Register()
        self.mhpmcounter23h = Register()
        self.mhpmcounter24h = Register()
        self.mhpmcounter25h = Register()
        self.mhpmcounter26h = Register()
        self.mhpmcounter27h = Register()
        self.mhpmcounter28h = Register()
        self.mhpmcounter29h = Register()
        self.mhpmcounter30h = Register()
        self.mhpmcounter31h = Register()

    def find(self, reg_name):
        
        priv_dictionary = {

            "fflags"            : self.fflags,
            "frm"               : self.frm,
            "fcsr"              : self.fcsr,
            "ustatus"           : self.ustatus,
            "uie"               : self.uie,
            "utvec"             : self.utvec,
            "vstart"            : self.vstart,
            "vxsat"             : self.vxsat,
            "uscratch"          : self.uscratch,
            "uepc"              : self.uepc,
            "ucause"            : self.ucause,
            "utval"             : self.utval,
            "uip"               : self.uip,
            "cycle"             : self.cycle,
            "time"              : self.time,
            "instret"           : self.instret,
            "hpmcounter3"       : self.hpmcounter3,
            "hpmcounter4"       : self.hpmcounter4,
            "hpmcounter5"       : self.hpmcounter5,
            "hpmcounter6"       : self.hpmcounter6,
            "hpmcounter7"       : self.hpmcounter7,
            "hpmcounter8"       : self.hpmcounter8,
            "hpmcounter9"       : self.hpmcounter9,
            "hpmcounter10"      : self.hpmcounter10,
            "hpmcounter11"      : self.hpmcounter11,
            "hpmcounter12"      : self.hpmcounter12,
            "hpmcounter13"      : self.hpmcounter13,
            "hpmcounter14"      : self.hpmcounter14,
            "hpmcounter15"      : self.hpmcounter15,
            "hpmcounter16"      : self.hpmcounter16,
            "hpmcounter17"      : self.hpmcounter17,
            "hpmcounter18"      : self.hpmcounter18,
            "hpmcounter19"      : self.hpmcounter19,
            "hpmcounter20"      : self.hpmcounter20,
            "hpmcounter21"      : self.hpmcounter21,
            "hpmcounter22"      : self.hpmcounter22,
            "hpmcounter23"      : self.hpmcounter23,
            "hpmcounter24"      : self.hpmcounter24,
            "hpmcounter25"      : self.hpmcounter25,
            "hpmcounter26"      : self.hpmcounter26,
            "hpmcounter27"      : self.hpmcounter27,
            "hpmcounter28"      : self.hpmcounter28,
            "hpmcounter29"      : self.hpmcounter29,
            "hpmcounter30"      : self.hpmcounter30,
            "hpmcounter31"      : self.hpmcounter31,
            "vl"                : self.vl,
            "vtype"             : self.vtype,
            "vlenb"             : self.vlenb,
            "sstatus"           : self.sstatus,
            "sie"               : self.sie,
            "stvec"             : self.stvec,
            "scounteren"        : self.scounteren,
            "sscratch"          : self.sscratch,
            "sepc"              : self.sepc,
            "scause"            : self.scause,
            "stval"             : self.stval,
            "sip"               : self.sip,
            "satp"              : self.satp,
            "vsstatus"          : self.vsstatus,
            "vsie"              : self.vsie,
            "vstvec"            : self.vstvec,
            "vsscratch"         : self.vsscratch,
            "vsepc"             : self.vsepc,
            "vscause"           : self.vscause,
            "vstval"            : self.vstval,
            "vsip"              : self.vsip,
            "vsatp"             : self.vsatp,
            "hstatus"           : self.hstatus,
            "hedeleg"           : self.hedeleg,
            "hideleg"           : self.hideleg,
            "hcounteren"        : self.hcounteren,
            "hgatp"             : self.hgatp,
            "utvt"              : self.utvt,
            "unxti"             : self.unxti,
            "uintstatus"        : self.uintstatus,
            "uscratchcsw"       : self.uscratchcsw,
            "uscratchcswl"      : self.uscratchcswl,
            "stvt"              : self.stvt,
            "snxti"             : self.snxti,
            "sintstatus"        : self.sintstatus,
            "sscratchcsw"       : self.sscratchcsw,
            "sscratchcswl"      : self.sscratchcswl,
            "mtvt"              : self.mtvt,
            "mnxti"             : self.mnxti,
            "mintstatus"        : self.mintstatus,
            "mscratchcsw"       : self.mscratchcsw,
            "mscratchcswl"      : self.mscratchcswl,
            "mstatus"           : self.mstatus,
            "misa"              : self.misa,
            "medeleg"           : self.medeleg,
            "mideleg"           : self.mideleg,
            "mie"               : self.mie,
            "mtvec"             : self.mtvec,
            "mcounteren"        : self.mcounteren,
            "mscratch"          : self.mscratch,
            "mepc"              : self.mepc,
            "mcause"            : self.mcause,
            "mtval"             : self.mtval,
            "mip"               : self.mip,
            "pmpcfg0"           : self.pmpcfg0,
            "pmpcfg1"           : self.pmpcfg1,
            "pmpcfg2"           : self.pmpcfg2,
            "pmpcfg3"           : self.pmpcfg3,
            "pmpaddr0"          : self.pmpaddr0,
            "pmpaddr1"          : self.pmpaddr1,
            "pmpaddr2"          : self.pmpaddr2,
            "pmpaddr3"          : self.pmpaddr3,
            "pmpaddr4"          : self.pmpaddr4,
            "pmpaddr5"          : self.pmpaddr5,
            "pmpaddr6"          : self.pmpaddr6,
            "pmpaddr7"          : self.pmpaddr7,
            "pmpaddr8"          : self.pmpaddr8,
            "pmpaddr9"          : self.pmpaddr9,
            "pmpaddr10"         : self.pmpaddr10,
            "pmpaddr11"         : self.pmpaddr11,
            "pmpaddr12"         : self.pmpaddr12,
            "pmpaddr13"         : self.pmpaddr13,
            "pmpaddr14"         : self.pmpaddr14,
            "pmpaddr15"         : self.pmpaddr15,
            "tselect"           : self.tselect,
            "tdata1"            : self.tdata1,
            "tdata2"            : self.tdata2,
            "tdata3"            : self.tdata3,
            "dcsr"              : self.dcsr,
            "dpc"               : self.dpc,
            "dscratch"          : self.dscratch,

            "mcycle"            : self.mcycle,
            "minstret"          : self.minstret,
            "mhpmcounter3"      : self.mhpmcounter3,
            "mhpmcounter4"      : self.mhpmcounter4,
            "mhpmcounter5"      : self.mhpmcounter5,
            "mhpmcounter6"      : self.mhpmcounter6,
            "mhpmcounter7"      : self.mhpmcounter7,
            "mhpmcounter8"      : self.mhpmcounter8,
            "mhpmcounter9"      : self.mhpmcounter9,
            "mhpmcounter10"     : self.mhpmcounter10,
            "mhpmcounter11"     : self.mhpmcounter11,
            "mhpmcounter12"     : self.mhpmcounter12,
            "mhpmcounter13"     : self.mhpmcounter13,
            "mhpmcounter14"     : self.mhpmcounter14,
            "mhpmcounter15"     : self.mhpmcounter15,
            "mhpmcounter16"     : self.mhpmcounter16,
            "mhpmcounter17"     : self.mhpmcounter17,
            "mhpmcounter18"     : self.mhpmcounter18,
            "mhpmcounter19"     : self.mhpmcounter19,
            "mhpmcounter20"     : self.mhpmcounter20,
            "mhpmcounter21"     : self.mhpmcounter21,
            "mhpmcounter22"     : self.mhpmcounter22,
            "mhpmcounter23"     : self.mhpmcounter23,
            "mhpmcounter24"     : self.mhpmcounter24,
            "mhpmcounter25"     : self.mhpmcounter25,
            "mhpmcounter26"     : self.mhpmcounter26,
            "mhpmcounter27"     : self.mhpmcounter27,
            "mhpmcounter28"     : self.mhpmcounter28,
            "mhpmcounter29"     : self.mhpmcounter29,
            "mhpmcounter30"     : self.mhpmcounter30,
            "mhpmcounter31"     : self.mhpmcounter31,

            "mhpevent3"         : self.mhpevent3,
            "mhpevent4"         : self.mhpevent4,
            "mhpevent5"         : self.mhpevent5,
            "mhpevent6"         : self.mhpevent6,
            "mhpevent7"         : self.mhpevent7,
            "mhpevent8"         : self.mhpevent8,
            "mhpevent9"         : self.mhpevent9,
            "mhpevent10"        : self.mhpevent10,
            "mhpevent11"        : self.mhpevent11,
            "mhpevent12"        : self.mhpevent12,
            "mhpevent13"        : self.mhpevent13,
            "mhpevent14"        : self.mhpevent14,
            "mhpevent15"        : self.mhpevent15,
            "mhpevent16"        : self.mhpevent16,
            "mhpevent17"        : self.mhpevent17,
            "mhpevent18"        : self.mhpevent18,
            "mhpevent19"        : self.mhpevent19,
            "mhpevent20"        : self.mhpevent20,
            "mhpevent21"        : self.mhpevent21,
            "mhpevent22"        : self.mhpevent22,
            "mhpevent23"        : self.mhpevent23,
            "mhpevent24"        : self.mhpevent24,
            "mhpevent25"        : self.mhpevent25,
            "mhpevent26"        : self.mhpevent26,
            "mhpevent27"        : self.mhpevent27,
            "mhpevent28"        : self.mhpevent28,
            "mhpevent29"        : self.mhpevent29,
            "mhpevent30"        : self.mhpevent30,
            "mhpevent31"        : self.mhpevent31,

            "mvendorid"         : self.mvendorid,
            "marchid"           : self.marchid,
            "mimpid"            : self.mimpid,
            "mhartid"           : self.mhartid,

            "cycleh"            : self.cycleh,
            "timeh"             : self.timeh,
            "instreth"          : self.instreth,
            "hpmcounter3h"      : self.hpmcounter3h,
            "hpmcounter4h"      : self.hpmcounter4h,
            "hpmcounter5h"      : self.hpmcounter5h,
            "hpmcounter6h"      : self.hpmcounter6h,
            "hpmcounter7h"      : self.hpmcounter7h,
            "hpmcounter8h"      : self.hpmcounter8h,
            "hpmcounter9h"      : self.hpmcounter9h,
            "hpmcounter10h"     : self.hpmcounter10h,
            "hpmcounter11h"     : self.hpmcounter11h,
            "hpmcounter12h"     : self.hpmcounter12h,
            "hpmcounter13h"     : self.hpmcounter13h,
            "hpmcounter14h"     : self.hpmcounter14h,
            "hpmcounter15h"     : self.hpmcounter15h,
            "hpmcounter16h"     : self.hpmcounter16h,
            "hpmcounter17h"     : self.hpmcounter17h,
            "hpmcounter18h"     : self.hpmcounter18h,
            "hpmcounter19h"     : self.hpmcounter19h,
            "hpmcounter20h"     : self.hpmcounter20h,
            "hpmcounter21h"     : self.hpmcounter21h,
            "hpmcounter22h"     : self.hpmcounter22h,
            "hpmcounter23h"     : self.hpmcounter23h,
            "hpmcounter24h"     : self.hpmcounter24h,
            "hpmcounter25h"     : self.hpmcounter25h,
            "hpmcounter26h"     : self.hpmcounter26h,
            "hpmcounter27h"     : self.hpmcounter27h,
            "hpmcounter28h"     : self.hpmcounter28h,
            "hpmcounter29h"     : self.hpmcounter29h,
            "hpmcounter30h"     : self.hpmcounter30h,
            "hpmcounter31h"     : self.hpmcounter31h,
            "mcycleh"           : self.mcycleh,
            "minstreth"         : self.minstreth,
            "mhpmcounter3h"     : self.mhpmcounter3h,
            "mhpmcounter4h"     : self.mhpmcounter4h,
            "mhpmcounter5h"     : self.mhpmcounter5h,
            "mhpmcounter6h"     : self.mhpmcounter6h,
            "mhpmcounter7h"     : self.mhpmcounter7h,
            "mhpmcounter8h"     : self.mhpmcounter8h,
            "mhpmcounter9h"     : self.mhpmcounter9h,
            "mhpmcounter10h"    : self.mhpmcounter10h,
            "mhpmcounter11h"    : self.mhpmcounter11h,
            "mhpmcounter12h"    : self.mhpmcounter12h,
            "mhpmcounter13h"    : self.mhpmcounter13h,
            "mhpmcounter14h"    : self.mhpmcounter14h,
            "mhpmcounter15h"    : self.mhpmcounter15h,
            "mhpmcounter16h"    : self.mhpmcounter16h,
            "mhpmcounter17h"    : self.mhpmcounter17h,
            "mhpmcounter18h"    : self.mhpmcounter18h,
            "mhpmcounter19h"    : self.mhpmcounter19h,
            "mhpmcounter20h"    : self.mhpmcounter20h,
            "mhpmcounter21h"    : self.mhpmcounter21h,
            "mhpmcounter22h"    : self.mhpmcounter22h,
            "mhpmcounter23h"    : self.mhpmcounter23h,
            "mhpmcounter24h"    : self.mhpmcounter24h,
            "mhpmcounter25h"    : self.mhpmcounter25h,
            "mhpmcounter26h"    : self.mhpmcounter26h,
            "mhpmcounter27h"    : self.mhpmcounter27h,
            "mhpmcounter28h"    : self.mhpmcounter28h,
            "mhpmcounter29h"    : self.mhpmcounter29h,
            "mhpmcounter30h"    : self.mhpmcounter30h,
            "mhpmcounter31h"    : self.mhpmcounter31h,

        }
        
        if (reg_name in priv_dictionary):
            return priv_dictionary[reg_name]
        else:
            return None
